template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-cloudcentrik-developer}

# Database settings.
database:

  # the name of your JDBC driver
  #driverClass: org.h2.Driver
  driverClass: org.postgresql.Driver

  # the username
  #user: sa
  user: dagenslunch
  #user: ${JDBC_DATABASE_USERNAME}

  # the password
  #password: sa
  password: open123
  #password: ${JDBC_DATABASE_PASSWORD}

  # the JDBC URL
  #url: jdbc:h2:./target/example
  url: jdbc:postgresql://127.0.0.1:5432/dagenslunch
  #url: ${JDBC_DATABASE_URL}
  
  properties:
    charSet: UTF-8
    characterEncoding: UTF-8
    useUnicode: true
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# use the simple server factory if you only want to run on a single port
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8989
    type: https
    port: 9090
    keyStorePath: dagenslunch.keystore
    keyStorePassword: dhaka_1971
    validateCerts: false
    

# Logging settings.
logging:
  level: INFO
  loggers:
    net.cloudcentrik.dagenslunch: INFO
    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: INFO
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/dagenslunch-server.log
      archivedLogFilenamePattern: /tmp/dagenslunch-server-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 1MB
      
# the key needs to match the suffix of the renderer
  
     
#commandline commands
#data migration
#java -jar target/dagenslunch-1.1.0-SNAPSHOT.jar db migrate local_config.yml
#running server
#java -jar target/dagenslunch-1.1.0-SNAPSHOT.jar server local_config.yml
#java --add-modules java.xml.bind -jar target/dagenslunch-1.1.0-SNAPSHOT.jar server local_config.yml
